name: Github Projects
markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "autolink", "fenced_code_blocks", "highlighter"]
pygments: true
exclude: [.git, .gitignore, .project, Gemfile, Gemfile.lock]